name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Build with Gradle
      env:
        GRADLE_SCAN_PUBLISH: true
      run: sh ./gradlew build
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: libs
        path: build/libs
    - name: Upload Test Results
      uses: actions/upload-artifact@v1
      with:
        name: tests
        path: build/reports/tests/test
    - name: Upload Static Analysis
      uses: actions/upload-artifact@v1
      with:
        name: analysis
        path: build/reports/detekt
  artifactory-publish:
    needs: build
    runs-on: ubuntu-latest
    name: Publish to Artifactory
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Download libs
        uses: actions/download-artifact@v1
        with:
          name: libs
          path: build/libs
      - name: Publish to Artifactory
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
        run: sh ./gradlew artifactoryPublish -PbintrayUser=$BINTRAY_USER -PbintrayKey=$BINTRAY_KEY
  maven-snapshot-publish:
    needs: build
    runs-on: ubuntu-latest
    name: Publish to Maven Central Snapshot
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Download libs
        uses: actions/download-artifact@v1
        with:
          name: libs
          path: build/libs
      - name: Sign and publish to Maven Central
        env:
          SIGNING_KEY_ENCODED: ${{ secrets.SIGNING_KEY_ENCODED }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          MAVEN_CENTRAL_USER: ${{ secrets.MAVEN_CENTRAL_USER }}
          MAVEN_CENTRAL_KEY: ${{ secrets.MAVEN_CENTRAL_KEY }}
        run: >-
          sh ./gradlew sign publishAllPublicationsToMavenCentralSnapshotsRepository
          -PsigningKeyEncoded=$SIGNING_KEY_ENCODED
          -PsigningPassword=$SIGNING_PASSWORD
          -PmavenCentralUser=$MAVEN_CENTRAL_USER
          -PmavenCentralKey=$MAVEN_CENTRAL_KEY