name: Release Build

on:
  push:
    tags:
      - '*'

jobs:
  release-build:
    runs-on: ubuntu-latest
    name: Release Build
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Build with Gradle
      env:
        GRADLE_SCAN_PUBLISH: true
      run: sh ./gradlew build
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: libs
        path: build/libs
    - name: Upload Test Results
      uses: actions/upload-artifact@v1
      with:
        name: tests
        path: build/reports/tests/test
    - name: Upload Static Analysis
      uses: actions/upload-artifact@v1
      with:
        name: analysis
        path: build/reports/detekt
  bintray-publish:
    needs: tag-build
    runs-on: ubuntu-latest
    name: Publish to Bintray
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Download libs
        uses: actions/download-artifact@v1
        with:
          name: libs
          path: build/libs
      - name: Deploy to Bintray
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
        run: sh ./gradlew bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayKey=$BINTRAY_KEY
